ui <- shiny::navbarPage("deskPlink",
  shiny::tabPanel("Main",
    shiny::sidebarLayout(
      shiny::sidebarPanel(
        shiny::verbatimTextOutput("plinkpath"),
        shinyFiles::shinyDirButton("plinkpath", "Plink directory",
          "Please select folder with unzipped plink executables."),
        shiny::hr(),
        shiny::verbatimTextOutput("workpath"),
        shinyFiles::shinyDirButton("workpath", "Working directory",
          "Please select folder where plink's output files will be written."),
        shiny::hr(),
        shiny::verbatimTextOutput("vcfpath"),
        shinyFiles::shinyFilesButton("vcfpath", "VCF file",
          "Please select VCF with all samples genotypes.", multiple = FALSE),
        shiny::hr(),
        shiny::verbatimTextOutput("csvpath"),
        shinyFiles::shinyFilesButton("csvpath", "CSV file",
          "Please select CSV with all samples phenotypes.", multiple = FALSE),
        shiny::hr()),
    shiny::mainPanel(
      DT::dataTableOutput("phenotypes"),
      shiny::hr(),
      shiny::fluidRow(
        shiny::column(5, offset = 1,
          shiny::uiOutput("seltest_ui"),
          shiny::uiOutput("phencol_ui"),
          shiny::uiOutput("selcov_ui")),
        shiny::column(5, offset = 1,
          shiny::uiOutput("sexcol_ui"),
          shiny::uiOutput("malecode_ui"),
          shiny::uiOutput("femalecode_ui"))),
      shiny::uiOutput("runbutton_ui")))),
  shiny::tabPanel("Results",
    shiny::uiOutput("result_ui"),
    DT::dataTableOutput("results"),
    shiny::hr(),
    shiny::p("See upstream documentation for column specifications..."),
    shiny::a("mperm",
             href = "https://www.cog-genomics.org/plink/1.9/formats#mperm"),
    shiny::a("assoc",
             href = "https://www.cog-genomics.org/plink/1.9/formats#assoc"),
    shiny::a("model",
             href = "https://www.cog-genomics.org/plink/1.9/formats#model"),
    shiny::a("linear/ logistic",
             href = "https://www.cog-genomics.org/plink/1.9/formats#assoc_linear"),
    ),
  shiny::tabPanel("Log",
    shiny::p("Only last run is shown. All *.log files are saved at working directory anyway."),
    shiny::verbatimTextOutput("cmd_text")))
